//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Different20Project_10_TriggerOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProcesss
    {
        public int ProcessId { get; set; }
        public Nullable<int> Process { get; set; }
    }
}
